name: mlcourse
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - eli5=0.11.0
  - ipywidgets=8.0.6
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pandas=1.4.4
  - pillow=9.5.0
  - plotly=5.12.0
  - pydot=1.4.2
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - statsmodels=0.14.0
  - wordcloud=1.9.1
  - pip
  - pip:
      - jupyter-book>=0.15.1
      - pydotplus>=2.0.2
      - pytesseract>=0.3.10
      - reverse-geocoder>=1.5.1
      - ua-parser>=0.16.1
      - user_agents>=2.2.0
      - pingouin>=0.5.4
      - prophet>=1.1.5
      - ipykernel>=6.29.4
      - black>=21.12b0
      - fonttools>=4.37.1
      - gdown>=4.7.1
      - ghp-import>=2.1.0
      - pre-commit>=2.20.0
      - pylatexenc>=2.10
      - pylint>=2.15.0
      - pyyaml>=6.0
      - sphinx-jupyterbook-latex>=0.5.2
      - xgboost==1.7.5
